### ISSUE TITLE
Clean the ogr/utils.py

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#103]
In #102, I've realized that most of the functions in [utils.py](https://github.com/packit-service/ogr/blob/master/ogr/utils.py) are never used.

We need to go through the functions and check if they are not used anywhere (please, control the packit codebase as well) and remove the unused ones.

----

In the other hand, we can move here the [LocalProject](https://github.com/packit-service/packit/blob/master/packit/local_project.py) or other git-related code from the Packit. Do we want OGR to be only remote API or git-helper?

**Comment by TomasTomecek** [comment]
LocalProject, our hero :heart:

**Comment by rpitonak** [comment]
> makes sense to me to add git-related functionality

+1
