### ISSUE TITLE
Remove PullRequests from list of Github Issues.

### ISSUE THREAD

**Issue by marusinm** [packit-service/ogr#107]
Based on [Github API doc](https://developer.github.com/v3/pulls/#labels-assignees-and-milestones):
>Every pull request is an issue, but not every issue is a pull request.

Therefore, in the case of Github, functions as `get_issue_list`, `get_issue_info` etc. are working also with Pull Requests and behavior isn't tested.

We should get rid of Pull Requests in functions working with Issues. Pagure doesn't have this problem. 

--------------
@lachmanfrantisek added:

To be able to be compatible with other git forges, let's differentiate between issues and pull-requests. (And do not allow working with GitHub issues, that are actually pull-requests. Issues and pull-requests are distinct sets.)

AC:

- [ ] Go through the issue related code in `GithubProject` and check if it does not return any PullRequest.
- [ ] Create test cases for that.

**Comment by mfocko** [comment]
`issue_list` should be ok.

Probably wrap `self.github_repo.get_issue` so it checks for PR? It's used in 5 (probably should be 6) places.

In `_get_all_issue_comments` it retrieves the issue by calling `get_pull`, is that a typo probably?

**Comment by lachmanfrantisek** [comment]
> issue_list should be ok.

Nice! Thanks for checking that -- some tests would be fine.

> Probably wrap self.github_repo.get_issue so it checks for PR? It's used in 5 (probably should be 6) places.

You can create some private method for that, that will be used in those five/six places. (This method should take care about getting the issue object and checking that it is not a PR.)

> In _get_all_issue_comments it retrieves the issue by calling get_pull, is that a typo probably?

Good catch! Definitely a bug!

**Comment by mfocko** [comment]
> Nice! Thanks for checking that -- some tests would be fine.

For now there's one checking the list of issues.
I'll add more for checking the thrown exceptions from other related functions later.

> You can create some private method for that, that will be used in those five/six places. (This method should take care about getting the issue object and checking that it is not a PR.)

Resolved by throwing exception from `_issue_from_github_object`, so I think there's no need for wrapper.
