### ISSUE TITLE
Deprecation policy

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#121]
Figure out a deprecated strategy for ogr, get inspired by packit: https://packit.dev/ [or django, ansible].

- [x] documentation
- [x] solution for method/classes

**Comment by mfocko** [comment]
@lachmanfrantisek Could you close it please? Should've been closed with #279

**Comment by lachmanfrantisek** [comment]
Closed by #279, https://github.com/packit-service/research/pull/14 and https://github.com/packit-service/research/pull/20
