### ISSUE TITLE
update contribution guide

### ISSUE THREAD

**Issue by marusinm** [packit-service/ogr#123]
Can we please update the contribution guide. Ogr now uses new zuul CI (or softwarefactory-project-zuul). 

I'm a little bit stuck on what should I do to make my tests passing when PR is opened. On my localhost, everything is working in the "old way" and tests are passing.

**Comment by TomasTomecek** [comment]
We're just trying zuul out, please let us know if it's inconsistent - this is the exact thing we are trying to investigate in coming weeks before we decide on switching from jenkins to zuul.

Zuul results should not be blocking.
