### ISSUE TITLE
Run tests on the OGR project itself

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#124]
- Try to have only one project for testing (ideally OGR itself in case of GitHub).
- Then it is easy for everyone to regenerate the test responses.

**Comment by TomasTomecek** [comment]
random contributors won't have edit access on ogr and might not be able to regen some offline files (just sayin')

how about creating a new project in our own namespaces, run the tests, trash the project?

**Comment by lachmanfrantisek** [comment]
> random contributors won't have edit access on ogr and might not be able to regen some offline files (just sayin')

Random contributor not, but for people interested in the project, we can add access to that one project easily.


> how about creating a new project in our own namespaces, run the tests, trash the project?

Yes, that would be another solution.
