### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#125]
It would be nice to finally start implementing the GitLab support.

We can probably combine the code from GitHub and the already present code.

The documentation can be found here: https://python-gitlab.readthedocs.io/en/stable/

**Comment by TomasTomecek** [comment]
It would be awesome, if this worked with our internal gitlab instance.

**Comment by lachmanfrantisek** [comment]
> It would be awesome, if this worked with our internal gitlab instance.

Yes, it needs to be handled in the same way as with Pagure, where we can have multiple `PagureService` instances with different `instance_url`.
