### ISSUE TITLE
missing annotations library for testing

### ISSUE THREAD

**Issue by jscotka** [packit-service/ogr#13]
after installing `ogr` via ``pip3 install .``
I wanted to run make check ``PYTHONPATH=`pwd` pytest-3 -v ./tests/``

it leads to errors like:
```
E     File "/home/jscotka/git/userspace-containerization/ogr/ogr/abstract.py", line 1
E       from __future__ import annotations
E                                        ^
E   SyntaxError: future feature annotations is not defined
```

seems that annotations module is not accessible in ``python3-3.6.8-1.fc28.x86_64`` by default

**Comment by jpopelka** [comment]
Yes, per [PEP 563](https://www.python.org/dev/peps/pep-0563/#abstract) it requires python 3.7

**Comment by jscotka** [comment]
From my perspective this is not good. from several reasons:
 * it is not possible to use it on Fedora28 directly. Yep, there is possible to install python37 too, but it is not default intepreter
 * other __stable__ systems may not support python3.7 maybe some debian stable, but no idea there
 * RHEL7 via RHSCL supports just python36
 * RHEL8 contains python36 , probably support of python37 will be added in future, but nobody knows if and when
 * as Jirka posted the comment in python37 it is still in ``__future__`` module
 * Is planned to incorporate it directly to python40 what is not our target.

Otherwise I understand that it is very useful feature, but not sure if we should deal with that in case it is not planned to add it to python3 as default module.

**Comment by lachmanfrantisek** [comment]
Let's discuss this at the meeting next week. (There are multiple new python features, that can be used or should be avoided.)

We can avoid only the import, not the type annotations in general.

**Comment by TomasTomecek** [comment]
> From my perspective this is not good. from several reasons:
> 
>     * it is not possible to use it on Fedora28 directly. Yep, there is possible to install python37 too, but it is not default intepreter

F28 will be EOL soonish, we try to use F29 wherever we can, precise dates:

    2019-05-07: Fedora 30 Final Release (GA) (Target #1)

so F28 will EOL in May/June).

>     * other **stable** systems may not support python3.7 maybe some debian stable, but no idea there

honestly, I don't think we care about those platforms now: we have this library for sake of us, so we can use it and our target platform is a F29 container at the moment; we can discuss this and align our expectations

>     * RHEL7 via RHSCL supports just python36

^

>     * RHEL8 contains python36 , probably support of python37 will be added in future, but nobody knows if and when

^^

> Otherwise I understand that it is very useful feature, but not sure if we should deal with that in case it is not planned to add it to python3 as default module.

Usually python devs put these modules to pypi so people can install it for older versions. We just need to do some research I guess
