### ISSUE TITLE
Look at possibility for reseting or get rid off checkes in GitHub

### ISSUE THREAD

**Issue by phracek** [packit-service/ogr#133]
TLDR: Investigate if it is possible to reset PR/commit flags. (*added by @lachmanfrantisek*)

----

I solved a problem with reset Copr build statuses.
Like can be seen here: https://github.com/packit-service/hello-world/pull/9

It would be nice to look at the possibility if in case of the pull request is not created by a collaborator to get rid of check statuses. Like nothing is shown and the pull request can not be merged.

**Comment by TomasTomecek** [comment]
what is the ask here? could you please write down what do you expect to be done?

**Comment by lachmanfrantisek** [comment]
> what is the ask here? could you please write down what do you expect to be done?

I've already changed the description.

**Comment by TomasTomecek** [comment]
So: can't fix? https://github.com/packit-service/packit-service/issues/140#issuecomment-552965285

**Comment by lachmanfrantisek** [comment]
It's not possible to do it -- we can only override them. (There is nothing like `pull-request` status in GitHub, it's only a `commit-status`, so it's de-facto refreshed when the PR git-head changes.)
