### ISSUE TITLE
the url in an issue object is the API url

### ISSUE THREAD

**Issue by dustymabe** [packit-service/ogr#146]
Just checking to see what is the desired behavior. I create an issue and then print the url from the created issue. I'd then like to open that url in a web browser and have it go to the graphical UI and not the API.

For example:

```
>>> i = project.create_issue('TestIssue', 'foo bar baz')
>>> print(i.url)
https://pagure.io/api/0/dusty/failed-composes/issue/2244
```

But what I really want is the url to the web frontent. So `i.url.replace('api/0/','')`. What is the intended behavior?

**Comment by lachmanfrantisek** [comment]
Good catch!

You are right. The web-url would be more useful.

**Comment by lachmanfrantisek** [comment]
Related line:

https://github.com/packit-service/ogr/blob/master/ogr/services/pagure.py#L638

Here is a function that we are calling:

```python
def _get_project_url(self, *args, add_fork_part=True, add_api_endpoint_part=True):
```

Using this parameter should be enough:

```python
 add_api_endpoint_part=False
```
