### ISSUE TITLE
Mention GitLab support in README

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#157]
Since we [now](https://github.com/packit-service/ogr/pull/150) support GitLab, we need to update our README to show it.

+ [ ] and provide brief docs how to use it (@TomasTomecek had to google a bit)

**Comment by rpitonak** [comment]
also a new release, WDYT?

**Comment by TomasTomecek** [comment]
... and add to readme after the release?

**Comment by lachmanfrantisek** [comment]
But please, wait for #156 (I need to add another test for it).

**Comment by lachmanfrantisek** [comment]
It looks like we need to wait for a group of issues #158

**Comment by lachmanfrantisek** [comment]
The issues are resolved so we are ready to go!

(Let's release a new version and change the Readme after that as Tomas suggested.)

**Comment by lachmanfrantisek** [comment]
The release was done, we are ready for this change!

**Comment by TomasTomecek** [comment]
```
Library for one API for many git forges. (e.g. GitHub, GitLab, Pagure).
Currently supported git forges:

    GitHub
    GitLab
    Pagure
```
I guess this is done?
