### ISSUE TITLE
Add method for loading instances from dict

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#159]
In [packit](https://github.com/packit-service/packit) and [upsint](https://github.com/packit-service/upsint/), we need to load authentication for services from files.

It would be nice to have a method for loading instances from `dict` so we can use it from multiple projects.

```python
>>> from ogr import get_instances_from_dict
>>> get_instances_from_dict({
...    "github.com": {"token": "abcd"},
...    "pagure.io": {"token": "defg"},
...    "src.fedoraproject.org": {"token": "asdasdasda"},
... })
[
    GithubService(token="abcd"),
    PagureService(instance_url="https://pagure.io", token="defg"),
    PagureService(instance_url="https://src.fedoraproject.org", token="asdasdasda"),
]
```

**Comment by TomasTomecek** [comment]
would be nice to see the dict definition before working on an implementation

**Comment by lachmanfrantisek** [comment]
> would be nice to see the dict definition before working on an implementation

I've proposed one in the description.

key: "server_url"
value: dict with arguments passed to `__init__`

**Comment by lachmanfrantisek** [comment]
This approach is good for most use-cases but does not allow custom mapping. (When the mapping url->servise-type is not known to us.)

We can add some optional argument for that:

```python
{
    "my.gtlb": {
        "type": "gitlab",
        "token": "abcd",
        "ssl_verify" : False
    }
}
```

**Comment by lachmanfrantisek** [comment]
@TomasTomecek Feel free to discuss the format in the PR: #160
