### ISSUE TITLE
Replace git-wrapping code with new or existing library

### ISSUE THREAD

**Issue by jpopelka** [packit-service/ogr#178]
Investigate existing libraries (example https://github.com/release-depot/git_wrapper).
Decide whether to use an existing library or move our [git-related code](https://github.com/packit-service/ogr/blob/master/ogr/utils.py) (check for all occurrences of "git" through the code) into a new library.
Use such library in ogr.

**Comment by Hojang2** [comment]
Hi, I am working on this issue and I tried to implement GitPython library.
Here is [my fork](https://github.com/Hojang2/ogr)

**Comment by jpopelka** [comment]
@Hojang2 Nice! We need you to create a Pull Request from https://github.com/Hojang2/ogr/tree/GitPython_implementation -> https://github.com/packit-service/ogr

**Comment by Hojang2** [comment]
Hi, I am working on this issue and I tried to implement the GitPython library.
Here is  [my PR](https://github.com/packit-service/ogr/pull/274)

**Comment by lachmanfrantisek** [comment]
Sorry, the #277 has wrong issue number for autoclosing.
