### ISSUE TITLE
Investigate 'open' x 'opened' status for Issues and PullRequests

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#193]
We are using `open` in the status enums, but `closed`.

Currently, we need to replace that for GitLab manually and GitHub probably needs that fix as well. I am not sure about Pagure.

Ideally, we need to change our API, but we have some usages in other projects:

- [ ] packit
    - https://github.com/packit-service/packit/blob/master/tests/testsuite_basic/conftest.py#L114 (just a test)
- [x] packit-service (no occurences found)
- [ ] release-bot
    - https://github.com/user-cont/release-bot/blob/master/release_bot/github.py#L308

**Comment by lachmanfrantisek** [comment]
@mfocko I hope it's fixed in your PR: #276 

Can we close this and fix potential problems in the packit / release-bot.

**Comment by mfocko** [comment]
I'm not aware of changing that, I'll look into it

**Comment by lachmanfrantisek** [comment]
Thanks, you implemented it from scratch so it's probably fixed.

**Comment by lachmanfrantisek** [comment]
The `opened` is not used anywhere. We don't need to change anything.

---

See the screenshot from gitlab:
![Snímek z 2019-12-04 13-20-30](https://user-images.githubusercontent.com/20214043/70142468-94c57f80-1699-11ea-9eed-2240eedb4e66.png)

- `open` means state
- `opened` is used in description as a verb
