### ISSUE TITLE
Fix/implement get_issue_comments

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#205]
In abstract class `GitProject`, we have the following method:

```python
    def get_issue_comments(
        self, issue_id, filter_regex: str = None, reverse: bool = False
    ) -> List["IssueComment"]:
        """
        Get list of Issue comments.

        :param issue_id: int
        :param filter_regex: filter the comments' content with re.search
        :param reverse: reverse order of comments
        :return: [IssueComment]
        """
        raise NotImplementedError()
```

This issue is not implemented in `GithubProject`, but the real implementation should be in the `_get_all_issue_comments`.

```python
    def _get_all_issue_comments(self, issue_id: int) -> List[IssueComment]:
        issue = self.github_repo.get_pull(number=issue_id)
        return [
            self._issuecomment_from_github_object(raw_comment)
            for raw_comment in issue.get_issue_comments()
        ]
```

AC:
- [ ] Github/Pagure
    - [ ] implement the `get_issue_comments` with the code `_get_all_issue_comments` (There are some missing parameters.)
    - [ ] remove the `_get_all_issue_comments` and change its usage to `get_issue_comments`
    - [ ] make sure it works as expected
- [ ] Implement the `get_issue_comments` in `GitlabProject`
- [ ] create test(s) for that if they are not already there

**Comment by mfocko** [comment]
I'll take it.

**Comment by mfocko** [comment]
Are you sure this is only GitHub?
- GitLab throws `NotImplementedError`
- Pagure has it implemented the same way as GitHub

**Comment by lachmanfrantisek** [comment]
> Are you sure this is only GitHub?

Feel free to fix that in all implementations..;)

You can also add some shared code to the `services.base.BaseGitProject` as we did for pr comments. (If needed.)

**Comment by lachmanfrantisek** [comment]
I've updated the description to cover all implementations.
