### ISSUE TITLE
Adding collaborators to projects

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#216]
- [ ] Add the `add_to_collaborators` method to `abstract.GitProject`. (And raise `NotImplementedError`.)
- [ ] Implement the method for all forges (GitHub, GitLab, Pagure).
- [ ] Add tests for this method.

Documentation:

- https://python-gitlab.readthedocs.io/en/stable/gl_objects/projects.html#project-members
- https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html
- https://pagure.io/api/0/ ( >  Modify ACLs on a project ?)

**Comment by lachmanfrantisek** [comment]
Should be resolved by #244

**Comment by lachmanfrantisek** [comment]
Yes, I still want it because of [my project](https://gitlab.fi.muni.cz/xlachma1/figitool) based on OGR.

**Comment by mfocko** [comment]
few things regarding implementation

- GitHub
    - only for organizations: `pull`, `push`, `admin` - **using the default?**
- GitLab
    - `access_level` **what should be default?**
      ```
      10 => Guest access
      20 => Reporter access
      30 => Developer access
      40 => Maintainer access
      50 => Owner access # Only valid for groups
      ```

- Pagure
    - none (removes), `ticket`, `commit`, `admin` - **default?**

**Comment by lachmanfrantisek** [comment]
>     * only for organizations: `pull`, `push`, `admin` - **using the default?**

You can add collaborators for the project as well:

![Screenshot from 2020-02-14 08-56-45](https://user-images.githubusercontent.com/20214043/74512211-0dea1a00-4f08-11ea-9cd2-1bb67760e931.png)

**Comment by shreyaspapi** [comment]
Hey if this isn't solved yet, Can I give it a try?

**Comment by lachmanfrantisek** [comment]
> Hey if this isn't solved yet, Can I give it a try?

@shreyaspapi Yes, that would be nice. I hope you can find some abstraction that will work for all three implementations.

**Comment by shreyaspapi** [comment]
> > Hey if this isn't solved yet, Can I give it a try?
> 
> @shreyaspapi Yes, that would be nice. I hope you can find some abstraction that will work for all three implementations.

- Github 
     - permission – string ‘pull’, ‘push’ or ‘admin’ mentioned in [pygithub](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.add_to_collaborators)
    - The v3 of github api which pygithub uses, states - The permission to grant the collaborator. Only valid on organization-owned repositories. [reference](https://developer.github.com/v3/repos/collaborators/#add-user-as-a-collaborator)
```
Pull
Triage
Push
Admin
Maintain 
      
```

- Gitlab 
     - I can see it is equivalent to github
```
Guest access
Reporter access
Developer access
Maintainer access
Owner access # Only valid for groups
```

- Pagure
    - here it says [docs](https://pagure.io/api/0/#projects-tab)
    - Can you help here is there any more information about all the roles?
```
ticket
commit
admin
```

**Comment by lachmanfrantisek** [comment]
@mfocko you may take a look..;)

@shreyaspapi Yes, GitHub and GitLab looks good and the mapping in Pagure is reasonable.
