### ISSUE TITLE
PagureProject.full_repo_name touches service

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#220]
This property violates our rule that only methods with `get` can touch the real servers.

We can:

- Revert the change and stay with guessing.
- Change the property to `get_full_repo_name` (needs deprecation to original property)
- Change our mind and do not be strict about that. (And use properties instead of methods for objects.)
    - This will bring nicer user-experience, but maybe some confusion.
    - Maybe, we can leave only `__init__` offline?

**Comment by mfocko** [comment]
What about implementing the same way as in base class?

```python
fork = "fork/" if self.is_fork else ""
namespace = f"{self.namespace}/" if namespace else ""
return f"{fork}{namespace}{self.repo}"

**Comment by lachmanfrantisek** [comment]
> What about implementing the same way as in base class?

Yes, this is one of the solutions. I just wanted to get a common agreement on that.

**Comment by lachmanfrantisek** [comment]
After some short discussion, we would like to have properties strictly offline. => We need to implement the `full_repo_name` without touching API.

(Sorry @mfocko to forcing you to use the API..;)

**Comment by mfocko** [comment]
Consider it fixed
