### ISSUE TITLE
remove persistent storage + mocking from ogr after using requre

### ISSUE THREAD

**Issue by jscotka** [packit-service/ogr#225]
After there will be done these stuff:
 - [ ] https://github.com/packit-service/ogr/pull/201 will be merged
 - [ ] there will be fixed also ``packit`` to use ``requre``

then remove all mocking stuff from this project

**Comment by mfocko** [comment]
not valid anymore?

**Comment by lachmanfrantisek** [comment]
I hope so. @jscotka , can you confirm that?

**Comment by lachmanfrantisek** [comment]
I think we are done with thid, @jscotka feel free to reopen if you see something missing.
