### ISSUE TITLE
Factor out Comment

### ISSUE THREAD

**Issue by mfocko** [packit-service/ogr#230]
Part of #86

Structure of classes:

* _Comment_
  * _IssueComment_
    * GithubIssueComment
    * GitlabIssueComment
    * PagureIssueComment
  * _PRComment_
    * GithubPRComment
    * GitlabPRComment
    * PagurePRComment

suggested by @lachmanfrantisek in #228

* [x] Create a `Comment` abstract class
* [x] Implement base class for `Comment`
* [x] Implementation of services
  * [x] Github
  * [x] Gitlab
  * [x] Pagure
* [x] Update interface to include function for returning `Comment` object
  * [x] Deprecate functions (`*Project`) manipulating with comments (#121)
* [ ] Remove `Comment = TypeVar('Comment', IssueComment, PRComment)`
* [ ] Make service-specific  `__str__` to be compatible with parent's constructor
* [ ] Decide return types for services `PRComment` vs `GithubPRComment`

Maybe the implementation for specific service could take the `raw_comment` in constructor?

**Comment by mfocko** [comment]
Just a thought, shouldn't we reorganize the file structure?
if we end up with separate classes (issue, comment, pr, release; not sure about more, only glanced through the github implementation) won't those files become... crowded?

**Comment by lachmanfrantisek** [comment]
> Just a thought, shouldn't we reorganize the file structure?
> if we end up with separate classes (issue, comment, pr, release; not sure about others, only glanced through the github implementation) won't those files become... crowded?

That's what I was thinking about for some time -- what about module (subfolder) for each implementation?

**Comment by mfocko** [comment]
you mean
```
github
└ issue
```
or
```
issue
└ github
```

**Comment by lachmanfrantisek** [comment]
> you mean

I mean the first one to be able to have imports like `from ogr.services.github import GithubService, GithubIssue`. (We don't need to change anything in the outside code since the imports stay the same.)

> Also I was wondering about create_issue for example... Do we want that static on Issue and pass the GithubProject (or eventually Repository object)?

The goal of the #86 is to have the objects dynamic. (And we cannot do that without forwarding some internal dynamic objects to the newly created instance.)

> What about chaining, e.g. project.get_issue(1).edit_description("aaaa").add_labels(["label"])?

Yes, this looks good!

(If it is a shortcut of running this:)
```python
first_issue = project.get_issue(1)
first_issue.edit_description("aaaa")
first_issue.add_labels(["label"])
```

So only returing `self` in each method.

**Comment by mfocko** [comment]
regarding the file structure for implementation... Should I use it for tests too?

**Comment by lachmanfrantisek** [comment]
> regarding the file structure for implementation... Should I use it for tests too?

Good point, it makes sense to me. I am only not sure if the loading of the response files doesn't break.

**Comment by mfocko** [comment]
> Good point, it makes sense to me. I am only not sure if the loading of the response files doesn't break.

ok... I'll just try to separate the comments to separate classes in those files for now?
