### ISSUE TITLE
Prepare file structure for object-specific methods (#86)

### ISSUE THREAD

**Issue by mfocko** [packit-service/ogr#232]
Split service implementations into separate directories, module for each class

- [x] Directory for each service
- [x] GitHub
  - [x] split implementation into multiple modules
  - [x] add `__init__.py` to make imports compatible
  - [x] update tests, since they store "full path" of caller
- [x] GitLab
  - [x] split implementation into multiple modules
  - [x] add `__init__.py` to make imports compatible
  - [x] update tests, since they store "full path" of caller
- [x] Pagure
  - [x] split implementation into multiple modules
  - [x] add `__init__.py` to make imports compatible
  - [x] update tests, since they store "full path" of caller

Related to #86

**Comment by mfocko** [comment]
- [ ] resolve circular dependencies...

**Comment by mfocko** [comment]
Do you want to regenerate all test data or "hacking" the classnames would do?

**Comment by lachmanfrantisek** [comment]
> Do you want to regenerate all test data or "hacking" the classnames would do?

If the "hacked" version does not differ in the important parts, you can use that approach. (E.g. dates and other non-used staff is not important to us)

Please, try to regenerate (locally) at least one test to check the difference.

**Comment by mfocko** [comment]
> If the "hacked" version does not differ in the important parts, you can use that approach. (E.g. dates and other non-used staff is not important to us)

it's just changing the "full class name"? basically `ogr.services.github` -> `ogr.services.github.project`, etc.
 
> Please, try to regenerate (locally) at least one test to check the difference.

Will do.
