### ISSUE TITLE
add reverse dependency testing to packit package

### ISSUE THREAD

**Issue by jscotka** [packit-service/ogr#237]
similar to https://github.com/packit-service/requre/issues/29
please add reverse dependency testing what will check that change will not break ``packit`` and in case it is broken, will raise that you have to create issue to packit to regenerate response files, or that it found bug in ogr.

**Comment by TomasTomecek** [comment]
+ packit-service

**Comment by lachmanfrantisek** [comment]
The packit reverse-dependency testing done in #241.

**Comment by lachmanfrantisek** [comment]
> + packit-service

I would wait for the stabilising the packit-service tests with that.

**Comment by TomasTomecek** [comment]
this is done, right?

**Comment by lachmanfrantisek** [comment]
> + packit-service

Do we want it? (Is packit enough? We can use p-s for the gate pipeline.)

**Comment by TomasTomecek** [comment]
p-s would be nice as well

**Comment by TomasTomecek** [comment]
I'm closing since this is now resolved.
