### ISSUE TITLE
Filter comments by author

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#240]
Add possibility to filter PR/issue comments by their author.

- [ ] Extend the methods of `GitProject` in `ogr/abstract.py`.
- [ ] Extend the `BaseGitProject` in `ogr/services/base.py` if needed.
- [ ] Implement the support both for PRs and issues. (Share as much code as possible -- implementation and pr/issue)
  - [ ] github
  - [ ] gitlab
  - [ ] pagure

**Comment by mfocko** [comment]
I'll take it
