### ISSUE TITLE
Determine the reason of project_create failure in Pagure namespace

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#245]
When creating a project in Pagure and setting the namespace, we get a general `not a valid choice`.

It would be useful to determine these two possibilities:

- non-existing namespace
- no permissions

---

The follow-up to #242 .

**Comment by mfocko** [comment]
Getting _Group information_ probably?
https://pagure.io/api/0/#groups
If it doesn't exist, we should get `not a valid choice` again, I hope...
If it exists, we should get info, right? Or can you have private group?

**Comment by lachmanfrantisek** [comment]
We are still interested.
