### ISSUE TITLE
0.1.0 release

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#25]
we need this b/c 0.0.2 doesn't have specfile

and I want to use packit to bring the release to fedora

**Comment by jpopelka** [comment]
> we need this b/c 0.0.2 doesn't have specfile

you mean 0.0.3 ?

**Comment by TomasTomecek** [comment]
why not 0.1.0, I think we can finally do a minor release since ogr is starting to be stable and generally usable by anyone
