### ISSUE TITLE
get installation ID: use code from pygithub once a new release is available

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#270]
https://github.com/PyGithub/PyGithub/pull/1135 is now merged

Use the code above to initiate GitHubService, related code (which we are using in the meantime):

pretty much drop this:
https://github.com/packit-service/ogr/blob/253e93bc87c079d0cd8f3dc87fc5e11f5078e53b/ogr/services/github_tweak.py#L11

Use the newly added functionality in pygithub here:
https://github.com/packit-service/ogr/blob/5729e29cb4e5bea7eb6ed68e1c573ca7f2d86051/ogr/factory.py#L142

Also please write a test case for this.

**Comment by pawelkopka** [comment]
@TomasTomecek I create PR what remove github tweak https://github.com/packit-service/ogr/pull/277. 
Can you extend your thought "Use the newly added functionality in pygithub"? I checked tests and it looks like get_instances_from_dict allow to use Github apps:  https://github.com/packit-service/ogr/blob/78eb94adb8ba248fee8938cac9a7acf1ac6343e3/tests/unit/test_factory.py#L242

**Comment by lachmanfrantisek** [comment]
> Can you extend your thought "Use the newly added functionality in pygithub"?

Yes, it "should" not be needed to change anything... Just please check that tests covers that scenario.

**Comment by pawelkopka** [comment]
Sorry for that. I updated PR.

**Comment by TomasTomecek** [comment]
The PR is now merged: I'm assuming we're good here and can close this issue.

@pawelkopka thank you very much!

**Comment by lachmanfrantisek** [comment]
Closed by #277
