### ISSUE TITLE
Inherit docstrings

### ISSUE THREAD

**Issue by mfocko** [packit-service/ogr#271]
Create a class decorator that would iterate through members of class and check if superclass has the same member with docstring, if so, copy the docstring.

Reduces the unnecessary copy-pasting of docstrings.

**Comment by TomasTomecek** [comment]
...or a metaclass :O

**Comment by lachmanfrantisek** [comment]
Still valid.

**Comment by lachmanfrantisek** [comment]
We agreed that we don't need that since we want the text to be present near the code. (The developer experience is better now.)
