### ISSUE TITLE
Integrations tests fails afters change in requre

### ISSUE THREAD

**Issue by pawelkopka** [packit-service/ogr#281]
After change in requre integrations tests, trying call property _is_write_mode_ .
Probably this _PersistentObjectStorage().is_write_mode_ need to be change to _PersistentObjectStorage().mode == StorageMode.write_

Error:
`AttributeError: 'PersistentObjectStorage' object has no attribute 'is_write_mode'`

**Comment by lachmanfrantisek** [comment]
It's interesting, that the reverse-dep tests passed:

https://github.com/packit-service/requre/pull/65
