### ISSUE TITLE
run our tests in Fedora CI

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#29]
this means to use standard-test-roles to wrap our tests so they can run when we create PRs on dist-git

see [python-docker's test wrapper](https://src.fedoraproject.org/rpms/python-docker/blob/master/f/tests) for more details

**Comment by lachmanfrantisek** [comment]
Probably outdated by the testing-farm. Reopen if you think we need the standard-test-roles.

**Comment by TomasTomecek** [comment]
testing farm and Fedora CI pipeline are complementary, but since we didn't find time to do this, let's leave this closed
