### ISSUE TITLE
RFE: get repo labels

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#301]
started porting upsint to ogr and realized that I can't get all labels defined on a repo

**Comment by lachmanfrantisek** [comment]
What about this:

https://github.com/packit-service/ogr/blob/2a0ba143f097addf1b00ac3ffc4b0855d6d0bd89/ogr/services/github/project.py#L413

**Comment by lachmanfrantisek** [comment]
But property can be added as well. I am not sure if the setter makes sense for this.

**Comment by TomasTomecek** [comment]
oh

```
11 months ago   |   def get_labels(self):
```

so it's not even new - I missed it
