### ISSUE TITLE
Issue setters (Pagure)

### ISSUE THREAD

**Issue by mfocko** [packit-service/ogr#302]
Implement updating title and description of issue on Pagure when the API allows it.

Blocked by: [Pagure's issue](https://pagure.io/pagure/issue/4704)

**Comment by lachmanfrantisek** [comment]
It's implemented but probably not deployed to `src.fedoraproject.org`.

But we can start working on it if we want: https://pagure.io/pagure/c/31280551ec2fdf282152abae2ff9d44f20faaf92?branch=master
