### ISSUE TITLE
how can I create a PR against my fork

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#307]
I am looking at this code:

https://github.com/packit-service/ogr/blob/b7c5333c4df64ecdf854a5375c207a789ca51a01/ogr/services/github/pull_request.py#L111

what if I want to create a PR against my fork and not the upstream project?

**Comment by lachmanfrantisek** [comment]
Gitlab probably supports forking of forks as well.

**Comment by lachmanfrantisek** [comment]
- [ ] We need to make sure this workflow works.
- [ ] Put this to docstring.

**Comment by saisankargochhayat** [comment]
Could you please point out the steps for tackling this issue?

**Comment by lachmanfrantisek** [comment]
We need to:
- [ ] check the methods and docstring if it is possible / it is well described
- [ ] check the implementations
  - [ ] ideally, create a test for each implementation, to have all combinations (fork -> fork, upstream -> upstream, fork -> upstream)
- [ ] update docstrings if it is not clear

Related code:
- abstract:
https://github.com/packit-service/ogr/blob/27a7276662a99c10ef163bb595325010d18f450e/ogr/abstract.py#L395-L412

- github:
https://github.com/packit-service/ogr/blob/27a7276662a99c10ef163bb595325010d18f450e/ogr/services/github/pull_request.py#L118-L124

- gitlab:
https://github.com/packit-service/ogr/blob/27a7276662a99c10ef163bb595325010d18f450e/ogr/services/gitlab/pull_request.py#L113-L119

- pagure:
https://github.com/packit-service/ogr/blob/27a7276662a99c10ef163bb595325010d18f450e/ogr/services/pagure/pull_request.py#L140-L146

(These are the static methods, but there is a wrapper method in the Project classes on top of them.)

**Comment by saisankargochhayat** [comment]
@lachmanfrantisek Thanks, I will create a PR fixing the functions.

**Comment by lachmanfrantisek** [comment]
@saisankargochhayat thank you, I'll take a look.

**Comment by TomasTomecek** [comment]
Given the PR is merged, we can close, right?

**Comment by mfocko** [comment]
> Given the PR is merged, we can close, right?

Yup, closed by #404
