### ISSUE TITLE
Support listing issues based on creator

### ISSUE THREAD

**Issue by dhodovsk** [packit-service/ogr#308]
Consider also other filtering options:

The options are:
https://github.com/PyGithub/PyGithub/blob/master/github/Repository.py#L2172-L2195

**Comment by lachmanfrantisek** [comment]
TODO: Check options for GitLab and Pagure as well.

**Comment by mfocko** [comment]
> TODO: Check options for GitLab and Pagure as well.

checked, it is possible

**Comment by lachmanfrantisek** [comment]
@mfocko thanks!
