### ISSUE TITLE
Unify external command invocation

### ISSUE THREAD

**Issue by jpopelka** [packit-service/ogr#33]
utils.py uses several different approaches to invoke an external command:

* [subprocess.Popen](https://github.com/packit-service/ogr/blob/master/ogr/utils.py#L103)
* [subprocess.check_call](https://github.com/packit-service/ogr/blob/master/ogr/utils.py#L122)
* [subprocess.check_output](https://github.com/packit-service/ogr/blob/master/ogr/utils.py#L171)

The recommended approach (since Python 3.5) is to use [subprocess.run](https://docs.python.org/3/library/subprocess.html#subprocess.run).

Also, there's lots of external libraries for this use case:
* http://amoffat.github.io/sh/
* https://www.pyinvoke.org/
* https://plumbum.readthedocs.io
* https://pexpect.readthedocs.io

**Comment by jscotka** [comment]
or there is also very nice wrapper in ``avocado`` https://avocado-framework.readthedocs.io/en/69.0/api/utils/avocado.utils.html#module-avocado.utils.process
could be used just as library and it is available in fedora and also on pip.

**Comment by TomasTomecek** [comment]
Wow, that's really impressive, probably the most comprehensive subprocess functionality I have ever seen. My main concern is that avocado would pull way too many dependencies: it would be lovely to have a minimal implementation of what they have, ideally in one of our projects.
