### ISSUE TITLE
improve pagure unit tests

### ISSUE THREAD

**Issue by sakalosj** [packit-service/ogr#334]
edited by @lachmanfrantisek :

TODO:
- Add tests for https://github.com/packit-service/ogr/pull/333 (better pagure error messages)
  - e.g. wrong URL, wrong token, not-found object,...

**Comment by lachmanfrantisek** [comment]
What exactly needs to be improved? Can you elaborate, please?

(We have no Pagure unit tests. There are only integration ones.)

**Comment by sakalosj** [comment]
> What exactly needs to be improved? Can you elaborate, please?
> 
> (We have no Pagure unit tests. There are only integration ones.)

created based on  https://github.com/packit-service/ogr/pull/333#pullrequestreview-360895023, but didn't check existing tests so incorectly thought that its units, sorry my bad

so it will be work on integration tests on pagure.service
this is what  you meant by command above?

**Comment by TomasTomecek** [comment]
this still needs better description

**Comment by lachmanfrantisek** [comment]
I've updated the title and description to make it clear also for others..;)
