### ISSUE TITLE
support pagination for get_issue_list

### ISSUE THREAD

**Issue by cverna** [packit-service/ogr#339]
Currently using a Pagure service the get_issue_list method returns only the last 20 issues of a project. This is because Pagure paginate the results, I have not looked at GitHub and GitLab but I guess it works the same.

Ideally `get_issue_list` should return a list of all the issues for a project and the pagination should be transparent to the user.

**Comment by lachmanfrantisek** [comment]
@cverna Thanks for the info!

It's related to this issue: #325 

For now, we need to:
- [ ] get all the issues in the `get_issue_list`
- [ ] add tests with the project having more than 20 issues
- [ ] check the other implementation and fix+test if needed
