### ISSUE TITLE
Validate the urls

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#342]
We have some URLs in the tests -- it would be nice to validate them.

*Originally reported by @jscotka :*
> Maybe one note, would be nice to test in tests that URLs are valid for github/gitlba/pagure, eg. via urllib download the diff and check if there are few expected lines.

**Comment by RafayGhafoor** [comment]
@lachmanfrantisek, I would like to work on this issue. Can you please elaborate the part about using urllib to download the diff and check if there are few expected lines.

What would be URL of diff and every URL of domain github/gitlab/pagure is to be tested for validity?

**Comment by lachmanfrantisek** [comment]
Nice!

> What would be URL of diff

That's the property we want to test. (See the related PR: #335 )

> every URL of domain github/gitlab/pagure is to be tested for validity?

I am not sure what you mean, but we would like to check all URL properties. (=Find all the properties that are URLs and check those.)
