### ISSUE TITLE
Supporting enterprise versions of Gitlab

### ISSUE THREAD

**Issue by saisankargochhayat** [packit-service/ogr#354]
I was wondering if OGR does support interacting with enterprise versions of Gitlab, when provided with an private token. I think Gitlab enterprise has the same set of API's as the public version, so is there a way to like provide the service url like for example - https://gitlab.cee.redhat.com and it would then try accessing repo's from that instead of publicly hosted Gitlab.

**Comment by lachmanfrantisek** [comment]
Hi @saisankargochhayat, thanks for your interest!

Yes, you can use `instance_url` argument for that when instantiating the service instance:

https://github.com/packit-service/ogr/blob/022e9dff7fd02e2f4d34ca836ac298127d7f5694/ogr/services/gitlab/service.py#L33-L36

Some testing was done on `git.gnome.org` and for internal instances `ssl_verify` argument may comes handy.

**Comment by lachmanfrantisek** [comment]
In `ogr/factory.py`, you can find some methods for picking the right instance for the project url:

https://github.com/packit-service/ogr/blob/022e9dff7fd02e2f4d34ca836ac298127d7f5694/ogr/factory.py#L68-L81

(Sadly, we don't have nice docs yet... #53 )

**Comment by saisankargochhayat** [comment]
@lachmanfrantisek Thanks a lot for the quick reply. 
I tried out some methods after instantiating with the `instance_url`, it seems to work with ssl_verify set to False, however fails when ssl_verify is set to true.

**Comment by lachmanfrantisek** [comment]
> it seems to work with ssl_verify set to False, however fails when ssl_verify is set to true.

The internal certificates were probably not discovered  -- @TomasTomecek knows how to get `requests` know about them.

**Comment by TomasTomecek** [comment]
> however fails when ssl_verify is set to true.

fails how? we can't help you if you don't provide us:
* logs
* code
* error messages

**Comment by lachmanfrantisek** [comment]
@TomasTomecek I think we know the problem and already discussed this situation some time ago:

- You have internal certs, but python/SSL does not know about them.
- I remember some env-var or something like that to get python/SSL know about it.

But a specific error might help.

**Comment by saisankargochhayat** [comment]
> > however fails when ssl_verify is set to true.
> 
> fails how? we can't help you if you don't provide us:
> 
>     * logs
> 
>     * code
> 
>     * error messages

Sorry about that. I have attached the same below - 
Error log - 
https://paste.ofcode.org/LDxYLXrkxzi7WvXKqwvb4x
Code (its a sample get issues) - 
```
from ogr.services.github import GithubService
from ogr.services.gitlab import GitlabService
from ogr.abstract import PRStatus

service = GitlabService(token=<my token>, instance_url="https://gitlab.cee.redhat.com")

ogr_project = service.get_project(
        repo="ai-ingest",
        namespace="data-hub"
)

print(ogr_project.get_owners)

issues = ogr_project.get_issue_list()
for i in issues:
    print(i.id)
```

**Comment by TomasTomecek** [comment]
Since this is using `requests` under the hood, you can tell requests to pick CAs from a specific file:
```
export REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt  
```

We should probably document this.

**Comment by lachmanfrantisek** [comment]
This is exactly what I had in mind.. Thanks!

**Comment by lachmanfrantisek** [comment]
I've created a new issue for the documentation part: https://github.com/packit-service/ogr/issues/356

I think we can close this one.

**Comment by saisankargochhayat** [comment]
Thanks once again for all the help!
