### ISSUE TITLE
new minor release

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#36]

**Comment by TomasTomecek** [comment]
I just made a PR request for a release version 0.1.0
 Here's a [link to the PR](https://github.com/packit-service/ogr/pull/37)

**Comment by jpopelka** [comment]
> [TomasTomecek](/TomasTomecek) reopened this

why?

**Comment by TomasTomecek** [comment]
Leave me alone.

**Comment by TomasTomecek** [comment]
I just made a PR request for a release version 0.1.0
 Here's a [link to the PR](https://github.com/packit-service/ogr/pull/38)

**Comment by TomasTomecek** [comment]
I just made a PR request for a release version 0.1.0
 Here's a [link to the PR](https://github.com/packit-service/ogr/pull/39)
