### ISSUE TITLE
provide a way to modify ACLs of repositories

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#364]
* We first to need to create an abstraction on top of all forges
* and then implement it for each

This is an example how pagure does it:
```python
mod_acls = {
        'user_type': 'group',
        'name': 'git-packit-team',
        'acl': 'admin',
}

req = requests.post(
        url + 'source-git/%s/git/modifyacls' % (project),
        headers=headers,
        verify=False,
        data=mod_acls
)
```

**Comment by lachmanfrantisek** [comment]
>     * We first to need to create an abstraction on top of all forges

This one would be hard since all of them have a different approach.

**Comment by TomasTomecek** [comment]
so maybe just implement it for pagure only e.g.

**Comment by lachmanfrantisek** [comment]
> so maybe just implement it for pagure only e.g.

We can at least try. (I wanted to use something similar here #216 )
