### ISSUE TITLE
source_project property for PR class

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#400]
Now, we have only `project` property in the PR class, but it's hard to get the source project. (It can be sometimes very tricky to pick the right repo from the OGR's user perspective.)

- [ ] add `source_project` property (abstract and implementations) returning the project with the source branch
- [ ] create tests:
  - [ ] basic PR from `fork` to `upstream`
  - [ ] renamed `fork`
  - [ ] renamed `upstream`
  - [ ] PR from `fork` to `fork`
  - [ ] PR from `upstream` to `upstream`
- [ ] ? `target_project` property that will replace the current `project` one to make it clear
  - [ ] don't forget to support both and deprecate the old one

**Comment by mfocko** [comment]
I'm thinking about the way to deprecate `project`. Easiest thing seems to be implementing it as a property.
Then arises the question whether we need to implement setters for `target`/`source` projects. In which I don't really see a point.

**Comment by lachmanfrantisek** [comment]
> I'm thinking about the way to deprecate `project`. Easiest thing seems to be implementing it as a property.

:+1:



> Then arises the question whether we need to implement setters for `target`/`source` projects. In which I don't really see a point.

We actually cannot edit them. So no, we don't need setters.
