### ISSUE TITLE
Creating pull requests from fork to other fork

### ISSUE THREAD

**Issue by mfocko** [packit-service/ogr#406]
After merging #404 there's no support only for creating PR from one fork to different fork.

PyGithub (GitHub API respectively) doesn't allow creating pull requests on a repository we're "merging" from.

-  [ ] implement getting other fork repository when creating PR against it (internal Repository should be enough)
   -  [ ] handle non-existing fork

**Comment by saisankargochhayat** [comment]
In a scenario where A(upstream) -> B(fork) -> C(fork)
Passing forkusername as None, seemed to create a PR to the parent fork, that is B, like here - 
https://github.com/AICoE/clai/pull/1
Does creating PR from one fork to different fork mean same?

**Comment by mfocko** [comment]
Looked at the project, it satisfies the "graph" you made, there it works fine.

I meant something like:
```
  A (upstream)
 / \
B   C
```

And then PR from B -> C or other way around.
