### ISSUE TITLE
add a way to set check results for a commit

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#54]
we need this in packit this sprint when we start building in copr

this should be implemented soonish and land in next release

relevant code for github:
https://github.com/packit-service/packit/blob/04793f16d5ced27b5e7fec7d963d650b065a4276/packit/watcher.py#L94

**Comment by lachmanfrantisek** [comment]
Already done:

https://github.com/packit-service/ogr/blob/master/ogr/abstract.py#L387
https://github.com/packit-service/ogr/blob/master/ogr/services/github.py#L262
https://github.com/packit-service/ogr/blob/master/ogr/services/pagure.py#L536
