### ISSUE TITLE
create target for makefile for regeneration testing yaml files

### ISSUE THREAD

**Issue by jscotka** [packit-service/ogr#61]
as integration tests needs regeneration stored yaml API communication.
Would be nice to add there target to be able to regenerate these files

**Comment by TomasTomecek** [comment]
This: https://github.com/packit-service/ogr/blob/aabae598d9203aa002a0f0b39a499b4ea9b87b73/tests/integration/test_github.py#L15

**Comment by lachmanfrantisek** [comment]
I've added targets for removing the response files in #84. 

The refresh is now only about `remove-response-files` and `check`...

**Comment by TomasTomecek** [comment]
Shall we close this then?

**Comment by lachmanfrantisek** [comment]
> Shall we close this then?

We do not have one target for that, but I am not sure if it is needed...

**Comment by TomasTomecek** [comment]
> ... but I am not sure if it is needed...

Yup, that's my point.

**Comment by lachmanfrantisek** [comment]
I don't need it. I'm removing the files directly...
