### ISSUE TITLE
libpagure.Pagure expects '/' not in repo attribute

### ISSUE THREAD

**Issue by jpopelka** [packit-service/ogr#67]
While debugging https://github.com/packit-service/packit/issues/305 I realized that it fails because [Pagure.create_basic_url()](https://pagure.io/libpagure/blob/17e240ea337e6962aa660b0cfd174ef6309f4162/f/libpagure/libpagure.py#_115) creates:
`https://src.fedoraproject.org//api/0/rpms/rpms/packit/pull-requests` which does not exist, correct is:
`https://src.fedoraproject.org//api/0/rpms/packit/pull-requests`.

The problem is that [OurPagure.repo](https://pagure.io/libpagure/blob/17e240ea337e6962aa660b0cfd174ef6309f4162/f/libpagure/libpagure.py#_115) attribute has a value `rpm/packit`, while libpagure probably expects it to be `packit` only.

Anybody has any idea whether this is a `ogr` or `packit` or `libpagure` issue?
I tend to think it's `ogr` issue, because [OurPagure.repo_name](https://github.com/packit-service/ogr/blob/master/ogr/services/our_pagure.py#L22) expects `/` in `self.repo`, which is probably not what `libpagure` wants.

And it gets even more puzzled when I tell you that [Pagure.create_basic_url() has changed](https://pagure.io/libpagure/c/075ee2f17c36b1c1477f72f711204945b609d5b1?branch=master) even more recently.

**Comment by lachmanfrantisek** [comment]
> Anybody has any idea whether this is a ogr or packit or libpagure issue?

Probably the problem in `OurPagure` or `PagureProject` in OGR.

> And it gets even more puzzled when I tell you that Pagure.create_basic_url() has changed even more recently.

Is this only a formatting change?

It is time to remove libpagure and communicate directly to Pagure API.
