### ISSUE TITLE
Change "Status" to  "Flag" in the class names

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#73]
What about changing `CommitStatus`/`PullRequestStatus` to `CommitFlag`/`PullRequestFlag`?

_Original discussion: https://github.com/packit-service/ogr/pull/71#pullrequestreview-240461635_

**Comment by jpopelka** [comment]
There's also [IssueStatus](https://github.com/packit-service/ogr/blob/master/ogr/abstract.py#L31)? (just spotted it in https://github.com/user-cont/release-bot/pull/231)
Should we change `IssueStatus` to `IssueFlag` as well?

**Comment by lachmanfrantisek** [comment]
> There's also [IssueStatus](https://github.com/packit-service/ogr/blob/master/ogr/abstract.py#L31)? (just spotted it in [user-cont/release-bot#231](https://github.com/user-cont/release-bot/pull/231))
> Should we change `IssueStatus` to `IssueFlag` as well?

Good point, we've missed two things:

- status: open/close
- flag: CI status
