### ISSUE TITLE
Add get_owner/get_owners method to project classes

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#88]
It would be useful to have a method for getting the owner(s) of the project.

If it is possible to have multiple owners, create `get_owners` and return list of strings.

**Comment by shreyanshrs44** [comment]
Hi, I would like to work on this issue. From where I should start to work on this?

**Comment by lachmanfrantisek** [comment]
It would be nice!

- In case of Pagure, you need to get the info from the API:
    - every instance has a documentation on /api/0/ (e.g. https://src.fedoraproject.org/api/0/)
    - the relevant would be part about `Project information`
    - since we are using this info in multiple was, we already have a function for that: [get_project_info](https://github.com/packit-service/ogr/blob/master/ogr/services/pagure.py#L309).

- In case of Github, we are working with pygithub objects:
    - you have the `Repository` instance in `self.github_repo`
    - [documentation for the class](https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.owner) (We need to return string, not the instance of [NamedUser](https://pygithub.readthedocs.io/en/latest/github_objects/NamedUser.html). The `login` is the attribute we want.)


- Please, add also the method to the [GitProject](https://github.com/packit-service/ogr/blob/d1f683b456c87b19720fe8a0b8b71061b65642b0/ogr/abstract.py#L280).

**Comment by marusinm** [comment]
@shreyanshrs44 are you currently working on this issue? I opened #88 which includes also feature in this issue. I would provide a solution in one PR.

**Comment by marusinm** [comment]
@shreyanshrs44 meanwhile I implemented this in #101 since I need this feature in another project.

> From where I should start to work on this?

If you'll refactor my code It may be a nice showcase on how to start work on such issues.

**Comment by lachmanfrantisek** [comment]
Already fixed in #101
