### ISSUE TITLE
String representations for classes

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#90]
It would be nice to implement `__str__` methods for all classes (e.g. `GithubProject`, `Issue`,...).

**Comment by lachmanfrantisek** [comment]
Some more info about `__str__` and `__repr__`:
- https://stackoverflow.com/questions/1436703/difference-between-str-and-repr#2626364
- https://www.journaldev.com/22460/python-str-repr-functions
- https://www.pythoncentral.io/what-is-the-difference-between-__str__-and-__repr__-in-python/

**Comment by shreyanshrs44** [comment]
Hi, I would like to work on this issue. One quick question what should __str__ method return for each classs ? I mean what should be mentioned in the representation of the object.

**Comment by lachmanfrantisek** [comment]
@shreyanshrs44 Thank you!

Just implement it as it is usual in Python -- I've linked some sources in the previous post.

I have no strict opinion about what precisely should be in `__str__`. Try adding useful info so it's easy to play with the classes. Send a pull-request and we can discuss that there.

**Comment by shreyanshrs44** [comment]
Sure !

**Comment by shreyanshrs44** [comment]
Hi I have created pull request here :https://github.com/packit-service/ogr/pull/93.

**Comment by lachmanfrantisek** [comment]
Solved in #98
